/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import java.util.ArrayList;

/**
 *
 * @author jason
 */
public class HangmanUI extends javax.swing.JFrame {

    /**
     * Creates new form HangmanUI
     */
    public HangmanUI() {
        initComponents();
        collectButtons();
        setUIDormant();
        
    }
    
    private GameInstance game;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitleText = new javax.swing.JLabel();
        jLabelObjectiveText = new javax.swing.JLabel();
        jButtonA = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonStartStop = new javax.swing.JButton();
        jLabelBody = new javax.swing.JLabel();
        jLabelNumAttempts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("applwindow"); // NOI18N

        jLabelTitleText.setFont(new java.awt.Font("Courier", 0, 36)); // NOI18N
        jLabelTitleText.setText("Hangman");
        jLabelTitleText.setToolTipText("the game");
        jLabelTitleText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTitleText.setName("jLabelTitleText"); // NOI18N

        jLabelObjectiveText.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        jLabelObjectiveText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObjectiveText.setText("X X X X X X X X X X");
        jLabelObjectiveText.setToolTipText("");
        jLabelObjectiveText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelObjectiveText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelObjectiveTextPropertyChange(evt);
            }
        });

        jButtonA.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonA.setText("A");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        jButtonJ.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonJ.setText("J");
        jButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJActionPerformed(evt);
            }
        });

        jButtonI.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonI.setText("I");
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIActionPerformed(evt);
            }
        });

        jButtonH.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonH.setText("H");
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });

        jButtonG.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonG.setText("G");
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGActionPerformed(evt);
            }
        });

        jButtonF.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonF.setText("F");
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });

        jButtonE.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonE.setText("E");
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonD.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonD.setText("D");
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });

        jButtonC.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonB.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonB.setText("B");
        jButtonB.setToolTipText("");
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButtonT.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonT.setText("T");
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTActionPerformed(evt);
            }
        });

        jButtonS.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonS.setText("S");
        jButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSActionPerformed(evt);
            }
        });

        jButtonR.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonR.setText("R");
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });

        jButtonQ.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonQ.setText("Q");
        jButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQActionPerformed(evt);
            }
        });

        jButtonP.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonP.setText("P");
        jButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPActionPerformed(evt);
            }
        });

        jButtonO.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonO.setText("O");
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });

        jButtonN.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonN.setText("N");
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNActionPerformed(evt);
            }
        });

        jButtonM.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonM.setText("M");
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMActionPerformed(evt);
            }
        });

        jButtonL.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonL.setText("L");
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLActionPerformed(evt);
            }
        });

        jButtonK.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonK.setText("K");
        jButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKActionPerformed(evt);
            }
        });

        jButtonZ.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonZ.setText("Z");
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });

        jButtonY.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonY.setText("Y");
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });

        jButtonX.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonX.setText("X");
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jButtonW.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonW.setText("W");
        jButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWActionPerformed(evt);
            }
        });

        jButtonV.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonV.setText("V");
        jButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVActionPerformed(evt);
            }
        });

        jButtonU.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        jButtonU.setText("U");
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });

        jButtonStartStop.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        jButtonStartStop.setText("Start Game");
        jButtonStartStop.setToolTipText("");
        jButtonStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartStopActionPerformed(evt);
            }
        });

        jLabelBody.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        jLabelBody.setText("Number of Attempts:");

        jLabelNumAttempts.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        jLabelNumAttempts.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelObjectiveText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitleText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonK)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonL)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonM)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonN)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonO)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButtonStartStop)
                                .addGap(124, 124, 124)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNumAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonP)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonQ)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonR)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonS)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonT))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonU)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonV)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonW)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonX)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonY)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonZ)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonA)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonB)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonC)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonD)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonF)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonG)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonH)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonI)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonJ)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleText)
                .addGap(18, 18, 18)
                .addComponent(jLabelObjectiveText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonA)
                        .addComponent(jButtonB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonJ)
                        .addComponent(jButtonI)
                        .addComponent(jButtonH)
                        .addComponent(jButtonG)
                        .addComponent(jButtonF)
                        .addComponent(jButtonE)
                        .addComponent(jButtonD)
                        .addComponent(jButtonC)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonT)
                    .addComponent(jButtonS)
                    .addComponent(jButtonR)
                    .addComponent(jButtonQ)
                    .addComponent(jButtonP)
                    .addComponent(jButtonO)
                    .addComponent(jButtonN)
                    .addComponent(jButtonM)
                    .addComponent(jButtonL)
                    .addComponent(jButtonK))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZ)
                    .addComponent(jButtonY)
                    .addComponent(jButtonX)
                    .addComponent(jButtonW)
                    .addComponent(jButtonV)
                    .addComponent(jButtonU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartStop)
                    .addComponent(jLabelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumAttempts))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("a"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("b"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("c"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("d"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("e"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("f"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("g"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonGActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("h"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonHActionPerformed

    private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("i"));
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonIActionPerformed

    private void jButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("j"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonJActionPerformed

    private void jButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("k"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonKActionPerformed

    private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("l"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonLActionPerformed

    private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("m"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonMActionPerformed

    private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("n"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonNActionPerformed

    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("o"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonOActionPerformed

    private void jButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("p"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonPActionPerformed

    private void jButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("q"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonQActionPerformed

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("r"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("s"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonSActionPerformed

    private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("t"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonTActionPerformed

    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("u"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonUActionPerformed

    private void jButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("v"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonVActionPerformed

    private void jButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("w"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonWActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("x"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("y"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonYActionPerformed

    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        game.incAttempts();
        jLabelObjectiveText.setText(game.updateObjective("z"));        
        jLabelNumAttempts.setText(game.getAttemptsStr());
    }//GEN-LAST:event_jButtonZActionPerformed

    private void jButtonStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartStopActionPerformed
        
        if (jButtonStartStop.getText().equals("Start Game")){
            jButtonStartStop.setText("Stop Game");
            setUIActive();
        }
        else
        {
            jButtonStartStop.setText("Start Game");
            setUIDormant();
        }
            
            
    }//GEN-LAST:event_jButtonStartStopActionPerformed

    private void jLabelObjectiveTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelObjectiveTextPropertyChange
        if (game != null && !((jLabelObjectiveText.getText().contains("_")) || 
                (jLabelObjectiveText.getText().contains("X"))))
        {
            jLabelObjectiveText.setText("Winner in " + game.getAttemptsStr() + " tries");
        }
    }//GEN-LAST:event_jLabelObjectiveTextPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanUI().setVisible(true);
            }
        });
    }
    
    public void setUIDormant(){
        jLabelNumAttempts.setText("0");
        jLabelObjectiveText.setText("X X X X X X X X X X");
        setButtons(false);
        
    }
    
    public void setUIActive(){
        game = new GameInstance();
        int l = game.newObjective();
        jLabelNumAttempts.setText("0");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i<l; i++) {
            sb.append("_ ");
        }
        jLabelObjectiveText.setText(sb.toString().trim());
        setButtons(true);
    }
    
    public void setButtons(boolean a){
        buttons.stream().forEach((b) -> {
            b.setEnabled(a);
        });
    }
    


    private ArrayList<javax.swing.JButton> buttons = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonStartStop;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JLabel jLabelBody;
    private javax.swing.JLabel jLabelNumAttempts;
    private javax.swing.JLabel jLabelObjectiveText;
    private javax.swing.JLabel jLabelTitleText;
    // End of variables declaration//GEN-END:variables

    public void collectButtons(){
        buttons.add(jButtonA);
        buttons.add(jButtonB);
        buttons.add(jButtonC);
        buttons.add(jButtonD);
        buttons.add(jButtonE);
        buttons.add(jButtonF);
        buttons.add(jButtonG);
        buttons.add(jButtonH);
        buttons.add(jButtonI);
        buttons.add(jButtonJ);
        buttons.add(jButtonK);
        buttons.add(jButtonL);
        buttons.add(jButtonM);
        buttons.add(jButtonN);
        buttons.add(jButtonO);
        buttons.add(jButtonP);
        buttons.add(jButtonQ);
        buttons.add(jButtonR);
        buttons.add(jButtonS);
        buttons.add(jButtonT);
        buttons.add(jButtonU);
        buttons.add(jButtonV);
        buttons.add(jButtonW);
        buttons.add(jButtonX);
        buttons.add(jButtonY);
        buttons.add(jButtonZ);
                
    }

}
